version: '2'
services:

 web:
  image: springio/skeleton-ws-spring-boot
  ports:
   - "8080:8080"
  links:
   - logstash
  networks:
   - front-tier

 elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
  container_name: elasticsearch
  environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - xpack.security.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65536
      hard: 65536
  mem_limit: 2g
  cap_add:
    - IPC_LOCK
  volumes:
    - esdata1:/usr/share/elasticsearch/data
  ports:
    - "9200:9200"
    - "9300:9300"
  networks:
    - back-tier

 logstash:
  image: logstash
  container_name: logstash
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
   - ./src/main/logstash/config:/etc/logstash/conf.d
  ports:
   - "5000:5000"
  links:
   - elasticsearch
  networks:
   - front-tier
   - back-tier

 kibana:
  image: kibana
  container_name: kibana
  environment:
   - ELASTICSEARCH_URL=http://elasticsearch:9200
  ports:
   - "5601:5601"
  links:
   - elasticsearch
  networks:
   - back-tier


volumes:
  esdata1:
    driver: local

networks:
  front-tier:
  back-tier:
   driver: bridge
